language: java

jdk:
  - oraclejdk7

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.12.0

addons:
  hosts:
    - hotstorage

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - mkdir -p "$HOME/bin"
  - export PATH="$PATH:$HOME/bin"
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > "$HOME/bin/docker-compose"
  - chmod +x "$HOME/bin/docker-compose"

script:
  - ./gradlew war
  - sudo docker-compose -f src/integrationTest/docker-compose.yml up -d --build
  - sudo docker ps -a
  - echo "INTEGRATION TEST"
  - ./gradlew check
  - sudo docker-compose -f src/integrationTest/docker-compose.yml down
  - echo "END TO END TEST"
  - ./gradlew setRadarEnvironmentForDocker
  - cd src/endToEndTest/dockerRadar/dcompose-stack/radar-cp-hadoop-stack
  - sudo ./install-radar-stack.sh
  - sudo docker ps -a
  - cd -
  - ./gradlew endToEndTest
  - cd src/endToEndTest/dockerRadar/dcompose-stack/radar-cp-hadoop-stack
  - sudo docker-compose -f docker-compose.yml down
  - cd -

after_script:
  - ./gradlew sendCoverageToCodacy