prettyPrint: true

servers:
  - url: https://localhost/api/

openAPI:
  info:
    title: RADAR-CNS Downstream REST APIs
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
