#=========================== Schema Registry ============================#
#List of Schema Registry instances
schema_registry:
  protocol: http
  host: localhost
  port: 8081
  unsafe: true
#============================ Rest Proxy ================================#
# if the producer_mode is rest, you must provide rest_proxy values
rest_proxy:
  protocol: http
  host: localhost
  port: 8082
  unsafe: true

#============================= Rest API =================================#
rest_api:
  protocol: http
  host: localhost
  port: 8080
  path: radar/api
  unsafe: true

##============================= Frontend =================================#
#frontend:
#  protocol: http
#  host: localhost
#  path: /frontend/
#  unsafe: true

#=============================== Test ===================================#
# time duration that mock data has to cover expressed in milliseconds.
duration_millis: 60000

#Possible value are direct, rest
producer_mode: rest

data:
  - topic: android_empatica_e4_acceleration
    sensor: EMPATICA_E4_v1_ACCELEROMETER
    frequency: 32.0
    file: accelerometer.csv
    key_schema: org.radarcns.kafka.ObservationKey
    value_schema: org.radarcns.passive.empatica.EmpaticaE4Acceleration
    value_fields: [x, y, z]
    minimum: -2.0
    maximum: 2.0
    maximum_difference: 1e-10
  - topic: android_empatica_e4_battery_level
    sensor: EMPATICA_E4_v1_BATTERY
    frequency: 1.0
    file: battery.csv
    key_schema: org.radarcns.kafka.ObservationKey
    value_schema: org.radarcns.passive.empatica.EmpaticaE4BatteryLevel
    value_fields: [batteryLevel]
    minimum: 0
    maximum: 1
    maximum_difference: 1e-10
  - topic: android_empatica_e4_blood_volume_pulse
    frequency: 64.0
    sensor: EMPATICA_E4_v1_BLOOD_VOLUME_PULSE
    file: blood_volume_pulse.csv
    key_schema: org.radarcns.kafka.ObservationKey
    value_schema: org.radarcns.passive.empatica.EmpaticaE4BloodVolumePulse
    value_fields: [bloodVolumePulse]
    minimum: -200
    maximum: 200
    maximum_difference: 1e-10
