#=========================== Schema Registry ============================#
#List of Schema Registry instances
schema_registry:
  protocol: https
  host: 10.131.135.158
  path: /schema/
  unsafe: true
#============================ Rest Proxy ================================#
# if the producer_mode is rest, you must provide rest_proxy values
rest_proxy:
  protocol: https
  host: 10.131.135.158
  path: /kafka/
  unsafe: true

#============================= Rest API =================================#
rest_api:
  protocol: https
  host: 10.131.135.158
  path: /api/
  unsafe: true

#============================= Frontend =================================#
frontend:
  protocol: https
  host: 10.131.135.158
  path: /frontend/
  unsafe: true

#=============================== Test ===================================#
# time duration that mock data has to cover expressed in milliseconds.
duration_millis: 60000

#Possible value are direct, rest
producer_mode: rest

data:
  - topic: android_empatica_e4_acceleration
    sensor: ACCELEROMETER
    frequency: 32.0
    file: accelerometer.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4Acceleration
    value_fields: [x, y, z]
    minimum: -2.0
    maximum: 2.0
    maximum_difference: 1e-10
  - topic: android_empatica_e4_battery_level
    sensor: BATTERY
    frequency: 1.0
    file: battery.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4BatteryLevel
    value_fields: [batteryLevel]
    minimum: 0
    maximum: 1
    maximum_difference: 1e-10
  - topic: android_empatica_e4_blood_volume_pulse
    frequency: 64.0
    sensor: BLOOD_VOLUME_PULSE
    file: blood_volume_pulse.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4BloodVolumePulse
    value_fields: [bloodVolumePulse]
    minimum: -200
    maximum: 200
    maximum_difference: 1e-10
  - topic: android_empatica_e4_electrodermal_activity
    frequency: 4.0
    sensor: ELECTRODERMAL_ACTIVITY
    file: electrodermal_activity.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4ElectroDermalActivity
    value_fields: [electroDermalActivity]
    minimum: 0.01
    maximum: 0.05
    maximum_difference: 1e-10
  - topic: android_empatica_e4_inter_beat_interval
    frequency: 1.0
    sensor: INTER_BEAT_INTERVAL
    file: inter_beat_interval.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4InterBeatInterval
    value_fields: [interBeatInterval]
    minimum: 0.5
    maximum: 1.1
    maximum_difference: 1e-10
  - topic: android_empatica_e4_temperature
    frequency: 4.0
    sensor: THERMOMETER
    file: thermometer.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4Temperature
    value_fields: [temperature]
    minimum: 20
    maximum: 55
    maximum_difference: 1e-10
