version: '3'

networks:
    simplestack:
      driver: bridge

services:
    #----------------------------------------#
    #            RADAR Hot Storage           #
    #----------------------------------------#
    hotstorage:
      image: radarcns/radar-hotstorage:0.1
      ports:
        - "27017:27017"
        - "28017:28017"
      networks:
        - simplestack
      depends_on:
        - wiremock
      environment:
        RADAR_USER: restapi
        RADAR_PWD: radar
        RADAR_DB: hotstorage

    #----------------------------------------#
    #             RADAR Rest Api             #
    #----------------------------------------#
    rest-api:
      image: radarcns/radar-restapi:dev
      depends_on:
        - hotstorage
        - wiremock
      networks:
        - simplestack
      ports:
        - "8080:8080"
      volumes:
        - "./volumes/radar:/usr/local/tomcat/conf/radar"


    #----------------------------------------#
    #             RADAR WireMock             #
    #----------------------------------------#
    wiremock:
      build: images/wiremock
      image: radarcns/wiremock
      networks:
        - simplestack
      ports:
        - "8089:8089"